{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePorts.http }}
      nodePort: {{ .Values.service.nodePorts.http }}
      {{- end }}
    {{- if .Values.compat.enabled }}
    - name: compat
      port: {{ .Values.service.ports.compat }}
      targetPort: compat
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePorts.compat }}
      nodePort: {{ .Values.service.nodePorts.compat }}
      {{- end }}
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "gateway.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
