{{- if .Values.config.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "casdoor.configName" . }}
  labels:
    {{- include "casdoor.labels" . | nindent 4 }}
data:
  app.conf: |
    appname = casdoor
    httpport = {{ .Values.config.httpPort }}
    runmode = {{ .Values.config.runMode }}
    copyrequestbody = {{ .Values.config.copyRequestBody }}
    driverName = {{ .Values.config.driverName }}
    dataSourceName = {{ required "config.dataSourceName is required" .Values.config.dataSourceName | quote }}
    dbName = {{ required "config.dbName is required" .Values.config.dbName }}
    redisEndpoint =
    defaultStorageProvider =
    isCloudIntranet = false
    authState = {{ .Values.config.authState | quote }}
    socks5Proxy = ""
    verificationCodeTimeout = 10
    initScore = 0
    logPostOnly = true
    isUsernameLowered = false
    origin = {{ .Values.config.origin | quote }}
    originFrontend =
    staticBaseUrl = {{ .Values.config.staticBaseUrl | quote }}
    isDemoMode = {{ .Values.config.isDemoMode }}
    batchSize = {{ .Values.config.batchSize }}
    enableErrorMask = {{ .Values.config.enableErrorMask }}
    enableGzip = {{ .Values.config.enableGzip }}
    inactiveTimeoutMinutes =
    ldapServerPort = 389
    radiusServerPort = 1812
    radiusSecret = {{ .Values.config.radiusSecret | quote }}
    quota = {{ .Values.config.quota }}
    logConfig = {{ .Values.config.logConfig }}
    initDataFile = {{ .Values.config.initDataFile | quote }}
    frontendBaseDir = {{ .Values.config.frontendBaseDir | quote }}
{{- end }}
