apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-provider-adapter.fullname" . }}
  labels:
    {{- include "ai-provider-adapter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "ai-provider-adapter.name" . }}
    app.kubernetes.io/instance: {{ include "ai-provider-adapter.instance" . }}
