apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.secretName" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ required "auth.password is required" .Values.auth.password | quote }}
