apiVersion: v1
kind: Secret
metadata:
  name: {{ include "edreamcrowd.fullname" . }}-backend-secret
  labels:
    {{- include "edreamcrowd.labels" . | nindent 4 }}
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: {{ required "backend.secret.SPRING_DATASOURCE_PASSWORD is required" .Values.backend.secret.SPRING_DATASOURCE_PASSWORD | quote }}
  JASYPT_ENCRYPTOR_PASSWORD: {{ required "backend.secret.JASYPT_ENCRYPTOR_PASSWORD is required" .Values.backend.secret.JASYPT_ENCRYPTOR_PASSWORD | quote }}
  CASDOOR_ACCESS_KEY: {{ .Values.backend.secret.CASDOOR_ACCESS_KEY | quote }}
  CASDOOR_ACCESS_SECRET: {{ .Values.backend.secret.CASDOOR_ACCESS_SECRET | quote }}
